//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Xml.Serialization;
using System.ComponentModel;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace Encryptor.Data
{

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.hcinsight.net/nucleus-test-data.xsd")]
    [XmlRootAttribute(Namespace = "http://www.hcinsight.net/nucleus-test-data.xsd",IsNullable = false)]
    public partial class Tests
    {

        private EnvironmentVariables environmentVariablesField;

        private FullyQualifiedClass[] testSuiteField;

        /// <remarks/>
        public EnvironmentVariables EnvironmentVariables
        {
            get
            {
                return this.environmentVariablesField;
            }
            set
            {
                this.environmentVariablesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItemAttribute(IsNullable = false)]
        public FullyQualifiedClass[] TestSuite
        {
            get
            {
                return this.testSuiteField;
            }
            set
            {
                this.testSuiteField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.hcinsight.net/nucleus-test-data.xsd")]
    public partial class EnvironmentVariables
    {

        private Param[] parametersField;

        /// <remarks/>
        [XmlArrayItemAttribute(IsNullable = false)]
        public Param[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.hcinsight.net/nucleus-test-data.xsd")]
    public partial class Param
    {

        private string nameField;

        private string codeField;

        private string typeField;

        private string clientField;

        private string valueField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.hcinsight.net/nucleus-test-data.xsd")]
    public partial class TestMethod
    {

        private Param[] parametersField;

        private string nameField;

        /// <remarks/>
        [XmlArrayItemAttribute(IsNullable = false)]
        public Param[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.hcinsight.net/nucleus-test-data.xsd")]
    public partial class FullyQualifiedClass
    {

        private TestMethod[] testMethodField;

        private string nameField;

        /// <remarks/>
        [XmlElementAttribute("TestMethod")]
        public TestMethod[] TestMethod
        {
            get
            {
                return this.testMethodField;
            }
            set
            {
                this.testMethodField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}
