//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace UIAutomation.Framework.Data.AutomationMapping
{
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hcinsight.net/AutomationMapping.xsd")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.hcinsight.net/AutomationMapping.xsd",
    IsNullable = false)]
  public partial class Mappings
  {

    private FullyQualifiedClass[] fullyQualifiedClassField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FullyQualifiedClass")]
    public FullyQualifiedClass[] FullyQualifiedClass
    {
      get { return this.fullyQualifiedClassField; }
      set { this.fullyQualifiedClassField = value; }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hcinsight.net/AutomationMapping.xsd")]
  public partial class FullyQualifiedClass
  {

    private Mapping[] mappingField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mapping")]
    public Mapping[] Mapping
    {
      get { return this.mappingField; }
      set { this.mappingField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
      get { return this.nameField; }
      set { this.nameField = value; }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hcinsight.net/AutomationMapping.xsd")]
  public partial class Mapping
  {

    private Param[] parametersField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public Param[] Parameters
    {
      get { return this.parametersField; }
      set { this.parametersField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
      get { return this.nameField; }
      set { this.nameField = value; }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hcinsight.net/AutomationMapping.xsd")]
  public partial class Param
  {

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
      get { return this.nameField; }
      set { this.nameField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
      get { return this.valueField; }
      set { this.valueField = value; }
    }
  }
}